from enum import StrEnum


class ErrorCode(StrEnum):
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    S3_ACCESS_ERROR = "S3_ACCESS_ERROR"
    DYNAMODB_ACCESS_ERROR = "DYNAMODB_ACCESS_ERROR"
